name: build

on: [push, pull_request]

jobs:
  build:
    name: Build WiiSX
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout pcsxgc
      uses: actions/checkout@master
      with:
        path: pcsxgc

    - name: Checkout libogc2
      uses: actions/checkout@master
      with:
        repository: extremscorner/libogc2
        path: libogc

    - name: add ppc gcc to PATH environment variable
      uses: myci-actions/export-env-var@1
      with:
        name: PATH
        value: $PATH:/opt/devkitpro/devkitPPC/bin

    - name: Export CFLAGS
      uses: myci-actions/export-env-var@1
      with:
        name: CFLAGS
        value: -O3 -fipa-pta -flto -DNDEBUG

    - name: Export CXXFLAGS
      uses: myci-actions/export-env-var@1
      with:
        name: CXXFLAGS
        value: -O3 -fipa-pta -flto -DNDEBUG

    - name: Checkout libfat
      uses: actions/checkout@main
      with:
        repository: extremscorner/libfat
        path: libfat
        
    - name: Build libogc2
      run: make install
      working-directory: libogc
      
    - name: Build libfat
      run: make ogc-install
      working-directory: libfat
      
    - name: Copy release files
      run: |
        cp -r Gamecube/release release
        cp -r Gamecube/release release_unai
      working-directory: pcsxgc

    - name: Build WiiSX (unai gpu)
      run: |
        mkdir build_wii_unai
        cmake -B build_wii_unai -DCMAKE_BUILD_TYPE=None -DWIISX_TARGET=NintendoWii -DGPU_PLUGIN=Unai
        cmake --build build_wii_unai
        mv build_wii_unai/WiiSX.dol release_unai/apps/wiiSX/boot.dol
      working-directory: pcsxgc

    - name: Upload soft (Unai) WiiSX
      uses: actions/upload-artifact@main
      with:
        name: WiiSX_Unai
        path: pcsxgc/release_unai
